name: clang-format-test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - 'include'
          - 'src'
          - 'apps'

    steps:
    - uses: actions/checkout@v6
    - uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '22'
        check-path: ${{ matrix.path }}
